demo1/demo1/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("web.urls", namespace="web"))
]

demo1/web/urls.py
from django.urls import path
from web.views import htmlPage,aboutPage


app_name = "web"

urlpatterns = [
    path('', htmlPage,name="home"),
    path('about-us', aboutPage,name="about")
]

demo1/web/models.py
from django.db import models

# Create your models here.

demo1/web/views.py
from django.shortcuts import render
from django.http.response import HttpResponse


def htmlPage(request):
    name = "Juog548"
    context = {
        "name" : name
    }
    return render(request, 'index.html',context=context)

def aboutPage(request):
    return render(request, 'about.html')

demo1/templates/about.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{title}}</title>
</head>
<body>
    <h1>About page</h1>
    <a href="{% url 'web:home' %}">Home</a>
</body>
</html>

demo1/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{title}}</title>
    <link rel="stylesheet" href="{% static 'styles/style.css' %}">
    <script src="{% static 'js/main.js' %}"></script>
</head>
<body>
    <h1 id="title">Hello {{name}} from web page</h1>
    <img src="{% static 'images/car.png' %}" alt="Image">
    <a href="{% url 'web:about' %}">About</a>
</body>
</html>